routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('report/:id', 'RawreportController@show')->name('rawreport.show');
Route::get('report', 'RawreportController@create')->name('rawreport.create');
Route::post('/', 'RawreportController@store')->name('rawreport.store');

Route::resources([
    'users' => 'UserController'
]);

Route::get('/', function () {
    return view('welcome');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token', 'id'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hwprofiles() {
        return $this->hasMany('App\Hwprofile');
    }

    public function campaigns() {
        return $this->hasMany('App\Campaign');
    }

    /**
     * Get the route key for the model.
     *
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public function path()
    {
        return route('user.show', $this);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::withCount('hwprofiles')->get();
        return response()->view('user.index', [
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $user->with(['hwprofiles.rawreports'])->get();
        return response()->view('user.show', [
            'user' => $user,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

}

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'Users')

@section('head')
@parent

<style>
    #userlistcontainer .panel-block {
        width: 100%;
        flex-grow: 1;
    }


</style>
@endsection

@section('content')


<div id="userlistcontainer" class="panel">
    <h2 class="panel-heading is-3">Users</h2>

        <div class="panel-block">
            <div class="control has-icons-left">
                <input type="text" class="input" placeholder="Search user">
                <span class="icon is-left">
                    <i class="fas fa-search" aria-hidden="true"></i>
                </span>
            </div>
        </div>
            @foreach($users as $user)
            <a href="{{ route('users.show', ['user' => $user->uuid]) }}" class="panel-block">
                <span class="panel-icon">
                    <i class="fas fa-book" aria-hidden="true"></i>
                  </span>
                  {{ $user->name }}
            </a>
            @endforeach


</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('title', 'User ' . $user->name)

@section('head')
@parent

<style>
    #userlistcontainer .panel-block {
        width: 100%;
        flex-grow: 1;
    }


</style>
@endsection

@section('content')


<div id="userlistcontainer" class="panel">
    <h2 class="panel-heading is-3">{{ $user->name }}</h2>

        <div class="panel-block">
            <div class="control has-icons-left">
                <input type="text" class="input" placeholder="Search user">
                <span class="icon is-left">
                    <i class="fas fa-search" aria-hidden="true"></i>
                </span>
            </div>
        </div>
{{ $user->toArray() }}
        @foreach($user->hwprofiles() as $profile)
            <a href="{{ route('users.show', ['user' => $user->uuid]) }}" class="panel-block">
                <span class="panel-icon">
                    <i class="fas fa-book" aria-hidden="true"></i>
                  </span>
                  {{ $profile->title }}
            </a>
        @endforeach


</div>
@endsection